version = 0.1

[default.deploy.parameters]
stack_name = "amie"
resolve_s3 = true
s3_prefix = "amie"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigin=\"*\""
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "us-west-2"
